version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/github_actions
    overwrite: yes

permissions:
  - object: /home/ubuntu/github_actions
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: root