spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intearn
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import:
      - aws.yml
