name: Deploy React

on:
  push:
    branches: master
    paths: 'frontend/**'
    
env:
  S3_BUCKET_NAME : intearn-frontend


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: frontend/node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn

      - name: Build
        working-directory: ./frontend
        run: yarn build
        env:
          CI: ""
          
      - name: Configure AWS credentials
        uses: aws-action/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ap-northeast-2

      - name: Upload to S3
        working-directory: ./frontend
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://$S3_BUCKET_NAME

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DISTRIBUTION_ID}} --paths "/*"
